<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Francisco Plaza Vega">

<title>Deep Learning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Deep_Learning_03_examples_02b_files/libs/clipboard/clipboard.min.js"></script>
<script src="Deep_Learning_03_examples_02b_files/libs/quarto-html/quarto.js"></script>
<script src="Deep_Learning_03_examples_02b_files/libs/quarto-html/popper.min.js"></script>
<script src="Deep_Learning_03_examples_02b_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Deep_Learning_03_examples_02b_files/libs/quarto-html/anchor.min.js"></script>
<link href="Deep_Learning_03_examples_02b_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Deep_Learning_03_examples_02b_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Deep_Learning_03_examples_02b_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Deep_Learning_03_examples_02b_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Deep_Learning_03_examples_02b_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">Contenidos</h2>
   
  <ul class="collapse">
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#librerías-y-datos" id="toc-librerías-y-datos" class="nav-link" data-scroll-target="#librerías-y-datos"><span class="header-section-number">2</span> Librerías y datos</a>
  <ul class="collapse">
  <li><a href="#librerías" id="toc-librerías" class="nav-link" data-scroll-target="#librerías"><span class="header-section-number">2.1</span> Librerías</a></li>
  <li><a href="#datos" id="toc-datos" class="nav-link" data-scroll-target="#datos"><span class="header-section-number">2.2</span> Datos</a></li>
  </ul></li>
  <li><a href="#pre-procesamiento" id="toc-pre-procesamiento" class="nav-link" data-scroll-target="#pre-procesamiento"><span class="header-section-number">3</span> Pre procesamiento</a>
  <ul class="collapse">
  <li><a href="#leer-imágenes" id="toc-leer-imágenes" class="nav-link" data-scroll-target="#leer-imágenes"><span class="header-section-number">3.1</span> Leer imágenes</a></li>
  <li><a href="#filtrar-imágenes-corruptas" id="toc-filtrar-imágenes-corruptas" class="nav-link" data-scroll-target="#filtrar-imágenes-corruptas"><span class="header-section-number">3.2</span> Filtrar imágenes corruptas</a></li>
  <li><a href="#distribución-de-las-dimensiones-de-las-imágenes" id="toc-distribución-de-las-dimensiones-de-las-imágenes" class="nav-link" data-scroll-target="#distribución-de-las-dimensiones-de-las-imágenes"><span class="header-section-number">3.3</span> Distribución de las dimensiones de las imágenes</a></li>
  <li><a href="#uso-de-data-augmentation" id="toc-uso-de-data-augmentation" class="nav-link" data-scroll-target="#uso-de-data-augmentation"><span class="header-section-number">3.4</span> Uso de <em>Data Augmentation</em></a></li>
  <li><a href="#balanceo-de-datos" id="toc-balanceo-de-datos" class="nav-link" data-scroll-target="#balanceo-de-datos"><span class="header-section-number">3.5</span> Balanceo de Datos</a></li>
  </ul></li>
  <li><a href="#cnns" id="toc-cnns" class="nav-link" data-scroll-target="#cnns"><span class="header-section-number">4</span> CNNs</a>
  <ul class="collapse">
  <li><a href="#la-base-del-modelo" id="toc-la-base-del-modelo" class="nav-link" data-scroll-target="#la-base-del-modelo"><span class="header-section-number">4.1</span> La base del modelo</a></li>
  <li><a href="#añadiendo-un-clasificador-a-la-cnn" id="toc-añadiendo-un-clasificador-a-la-cnn" class="nav-link" data-scroll-target="#añadiendo-un-clasificador-a-la-cnn"><span class="header-section-number">4.2</span> Añadiendo un clasificador a la CNN</a></li>
  </ul></li>
  <li><a href="#entrenamiento-de-la-cnn" id="toc-entrenamiento-de-la-cnn" class="nav-link" data-scroll-target="#entrenamiento-de-la-cnn"><span class="header-section-number">5</span> Entrenamiento de la CNN</a>
  <ul class="collapse">
  <li><a href="#ajuste-del-modelo-utilizando-un-generador-de-lotes-batch-generator" id="toc-ajuste-del-modelo-utilizando-un-generador-de-lotes-batch-generator" class="nav-link" data-scroll-target="#ajuste-del-modelo-utilizando-un-generador-de-lotes-batch-generator"><span class="header-section-number">5.1</span> Ajuste del modelo utilizando un generador de lotes (<em>batch generator</em>)</a></li>
  </ul></li>
  <li><a href="#probando-el-modelo" id="toc-probando-el-modelo" class="nav-link" data-scroll-target="#probando-el-modelo"><span class="header-section-number">6</span> Probando el modelo</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Deep Learning</h1>
<p class="subtitle lead">CNN: Ejemplo de <code>Gatos y Perros</code> en R</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Autor/a</div>
  <div class="quarto-title-meta-heading">Afiliación</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Francisco Plaza Vega <a href="mailto:francisco.plaza.v@usach.cl" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Ingeniería en Estadística
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<div class="example">
<p>Esta vez exploraremos un ejemplo práctico empleando la biblioteca <code>keras</code> en R, pero esta vez haremos la clasificación de imágenes desde cero, comenzando desde archivos locales de imagenes <code>JPEG</code> en el disco. En esta ocasión, usaremos los datos de clasificación binaria <a href="https://www.kaggle.com/c/dogs-vs-cats">Cats vs Dogs de Kaggle</a>.</p>
<p>Este ejemplo está basado en el tutorial de <a href="https://tensorflow.rstudio.com/examples/image_classification_from_scratch.html">Tensorflow para R</a>.</p>
</div>
</section>
<section id="librerías-y-datos" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Librerías y datos</h1>
<section id="librerías" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="librerías"><span class="header-section-number">2.1</span> Librerías</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tensorflow)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(keras)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tfdatasets)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># Para manejo de datos</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(imager) <span class="co"># Manipulación de imágenes</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret) <span class="co">#Evaluación de modelo</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="datos" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="datos"><span class="header-section-number">2.2</span> Datos</h2>
<section id="descarga-de-datos-en-bruto" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="descarga-de-datos-en-bruto"><span class="header-section-number">2.2.1</span> Descarga de datos en bruto</h3>
<p>Primero, descargaremos el archivo ZIP de 786M que contiene los datos en bruto. Notar el manejo y creación de carpetas, utilizando el directorio relativo de R (<code>"./</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">timeout =</span> <span class="dv">60</span> <span class="sc">*</span> <span class="dv">5</span>) <span class="co"># 5 minutes</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(url, <span class="at">destfile =</span> <span class="st">"./db/cats_and_dogs/kagglecatsanddogs_5340.zip"</span>) <span class="co"># (786.7 MB)</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Para ver un listado de todo lo que contiene el archivo zip:</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># zip::zip_list("./db/cats_and_dogs/kagglecatsanddogs_5340.zip") |&gt; tibble::as_tibble()</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>zip<span class="sc">::</span><span class="fu">unzip</span>(<span class="st">"./db/cats_and_dogs/kagglecatsanddogs_5340.zip"</span>, <span class="at">exdir =</span> <span class="st">"./db/cats_and_dogs/"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ahora tenemos una carpeta llamada <code>PetImages</code> que contiene dos subcarpetas, <code>Cat</code> y <code>Dog</code>. Cada subcarpeta contiene archivos de imágenes para cada categoría.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>path <span class="ot">=</span> <span class="st">"./db/cats_and_dogs/PetImages"</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>fs<span class="sc">::</span><span class="fu">dir_info</span>(path)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 18
  path         type   size permissions modification_time   user  group device_id
  &lt;fs::path&gt;   &lt;fct&gt; &lt;fs:&gt; &lt;fs::perms&gt; &lt;dttm&gt;              &lt;chr&gt; &lt;chr&gt;     &lt;dbl&gt;
1 …tImages/Cat dire…     0 rw-         2024-05-22 10:58:07 &lt;NA&gt;  &lt;NA&gt;     2.12e9
2 …tImages/Dog dire…     0 rw-         2024-05-22 10:57:59 &lt;NA&gt;  &lt;NA&gt;     2.12e9
# ℹ 10 more variables: hard_links &lt;dbl&gt;, special_device_id &lt;dbl&gt;, inode &lt;dbl&gt;,
#   block_size &lt;dbl&gt;, blocks &lt;dbl&gt;, flags &lt;int&gt;, generation &lt;dbl&gt;,
#   access_time &lt;dttm&gt;, change_time &lt;dttm&gt;, birth_time &lt;dttm&gt;</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="pre-procesamiento" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Pre procesamiento</h1>
<section id="leer-imágenes" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="leer-imágenes"><span class="header-section-number">3.1</span> Leer imágenes</h2>
<p>Leer datos de imágenes involucra adentrarse en el proceso de cargar e interpretar información visual de archivos de imagen en un formato que se pueda utilizar para análisis, manipulación o aprendizaje automático.</p>
<section id="leer-el-directorio-de-carpetas" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="leer-el-directorio-de-carpetas"><span class="header-section-number">3.1.1</span> Leer el directorio de carpetas</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>folder_list <span class="ot">&lt;-</span> <span class="fu">list.files</span>(path)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>folder_list</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Cat" "Dog"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>folder_path <span class="ot">&lt;-</span> <span class="fu">paste0</span>(path, <span class="st">"/"</span>, folder_list, <span class="st">"/"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>folder_path</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "./db/cats_and_dogs/PetImages/Cat/" "./db/cats_and_dogs/PetImages/Dog/"</code></pre>
</div>
</div>
<p>La salida mostrada presenta los nombres de subdirectorios o archivos presentes en el directorio <code>"./db/cats_and_dogs/PetImages"</code>. Cada entrada en la lista corresponde a una categoría específica, como <code>Cat</code> y <code>Dog</code>. Esta salida proporciona efectivamente una visión general del contenido dentro del directorio y sirve como un punto de partida valioso para tareas de procesamiento o análisis de datos adicionales. Al mostrar la salida en una nueva ventana, el fragmento de código asegura que los resultados sean fácilmente visibles e interpretables.</p>
</section>
<section id="leer-nombres-de-archivos" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="leer-nombres-de-archivos"><span class="header-section-number">3.1.2</span> Leer nombres de archivos</h3>
<p>Leer los nombres de los archivos implica extraer e interpretar los nombres de los archivos dentro de un directorio específico. Este proceso es un paso fundamental para entender la composición y estructura de un conjunto de datos no estructurados, como lo son las imágenes de este ejemplo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener nombres de archivos</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>file_name <span class="ot">&lt;-</span> <span class="fu">map</span>(folder_path, </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                 <span class="cf">function</span>(x) <span class="fu">paste0</span>(x, <span class="fu">list.files</span>(x))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                 ) <span class="sc">%&gt;%</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unlist</span>()</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Primeros 6 nombres de archivos</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(file_name)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "./db/cats_and_dogs/PetImages/Cat/0.jpg"    
[2] "./db/cats_and_dogs/PetImages/Cat/1.jpg"    
[3] "./db/cats_and_dogs/PetImages/Cat/10.jpg"   
[4] "./db/cats_and_dogs/PetImages/Cat/100.jpg"  
[5] "./db/cats_and_dogs/PetImages/Cat/1000.jpg" 
[6] "./db/cats_and_dogs/PetImages/Cat/10000.jpg"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Últimos 6 nombres de archivos</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(file_name)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "./db/cats_and_dogs/PetImages/Dog/9994.jpg"
[2] "./db/cats_and_dogs/PetImages/Dog/9995.jpg"
[3] "./db/cats_and_dogs/PetImages/Dog/9996.jpg"
[4] "./db/cats_and_dogs/PetImages/Dog/9997.jpg"
[5] "./db/cats_and_dogs/PetImages/Dog/9998.jpg"
[6] "./db/cats_and_dogs/PetImages/Dog/9999.jpg"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cantidad de archivos</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(file_name)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 23198</code></pre>
</div>
</div>
<p>El conjunto de datos de imágenes consta de 23198 archivos que se han extraído y almacenado con éxito desde la carpeta designada. Esta información proporciona una visión integral del volumen de datos accesibles, representando la diversidad y complejidad inherente al conjunto de datos. Al conocer la presencia de 23198 archivos de imágenes, podemos obtener una comprensión más profunda de los recursos disponibles para análisis, aprendizaje automático o desarrollo de modelos. Además, comprender el tamaño del conjunto de datos también ayuda a planificar estrategias de limpieza de datos, transformaciones y la selección de características apropiadas. Al utilizar esta información, podemos asegurar que los pasos subsiguientes en la exploración y utilización del conjunto de datos se lleven a cabo de manera eficiente y efectiva. Veamos 6 ejemplos de muestra que se seleccionarán para un análisis más detallado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionar imágenes aleatorias</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">99</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>sample_image <span class="ot">&lt;-</span> <span class="fu">sample</span>(file_name, <span class="dv">12</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar las imágenes en R</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>img <span class="ot">&lt;-</span> <span class="fu">map</span>(sample_image, load.image)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico de las imágenes</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>)) <span class="co"># Crea una grilla de 3 x 4</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">1</span>))</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="fu">map</span>(img, plot)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deep_Learning_03_examples_02b_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
Image. Width: 500 pix Height: 375 pix Depth: 1 Colour channels: 3 

[[2]]
Image. Width: 329 pix Height: 450 pix Depth: 1 Colour channels: 3 

[[3]]
Image. Width: 350 pix Height: 334 pix Depth: 1 Colour channels: 3 

[[4]]
Image. Width: 500 pix Height: 468 pix Depth: 1 Colour channels: 3 

[[5]]
Image. Width: 500 pix Height: 303 pix Depth: 1 Colour channels: 3 

[[6]]
Image. Width: 380 pix Height: 342 pix Depth: 1 Colour channels: 3 

[[7]]
Image. Width: 500 pix Height: 375 pix Depth: 1 Colour channels: 3 

[[8]]
Image. Width: 320 pix Height: 240 pix Depth: 1 Colour channels: 3 

[[9]]
Image. Width: 355 pix Height: 500 pix Depth: 1 Colour channels: 3 

[[10]]
Image. Width: 318 pix Height: 500 pix Depth: 1 Colour channels: 3 

[[11]]
Image. Width: 500 pix Height: 347 pix Depth: 1 Colour channels: 3 

[[12]]
Image. Width: 407 pix Height: 500 pix Depth: 1 Colour channels: 3 </code></pre>
</div>
</div>
</section>
<section id="dimensión-de-las-imágenes" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="dimensión-de-las-imágenes"><span class="header-section-number">3.1.3</span> Dimensión de las imágenes</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Descripción completa de la imagen</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>img <span class="ot">&lt;-</span> <span class="fu">load.image</span>(file_name[<span class="dv">2</span>])</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>img</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Image. Width: 300 pix Height: 281 pix Depth: 1 Colour channels: 3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dimensión de la imagen</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(img)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 300 281   1   3</code></pre>
</div>
</div>
<p>La imagen cargada es una imagen con 3 canales de color, y dimensiones 300x281 pixeles. Cada pixel está representado por 3 valores (3 canales de imagen). En el caso de imágenes en escala de grises, se tiene tan solo un canal de color.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Función para guardar altura, anchura y nombre de archivo de una imagen</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>get_dim <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  img <span class="ot">&lt;-</span> <span class="fu">load.image</span>(x) </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  df_img <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">height =</span> <span class="fu">height</span>(img),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">width =</span> <span class="fu">width</span>(img),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">filename =</span> x</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df_img)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="fu">get_dim</span>(file_name[<span class="dv">1</span>])</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  height width                               filename
1    375   500 ./db/cats_and_dogs/PetImages/Cat/0.jpg</code></pre>
</div>
</div>
<p>La función <code>get_dim()</code> carga una imagen utilizando la función <code>load.image()</code> y luego crea un data frame <code>df_img</code> que contiene tres columnas: <span class="green">altura, ancho y nombre del archivo</span>. Las dimensiones de las imágenes cargadas pueden ser luego guardadas en las columnas altura y ancho ( <span class="orange"><em>height</em></span> y <span class="orange"><em>width</em></span>), y el correspondiente nombre del archivo (con su respectiva ruta) es guardado en la columna <span class="orange"><em>filename</em></span>.</p>
</section>
</section>
<section id="filtrar-imágenes-corruptas" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="filtrar-imágenes-corruptas"><span class="header-section-number">3.2</span> Filtrar imágenes corruptas</h2>
<p>Cuando se trabaja con una gran cantidad de datos de imágenes del mundo real, es común <span class="green">encontrar imágenes corruptas que no pueden ser leídas</span>. Filtraremos las imágenes mal codificadas que no tienen el <em>string</em> <code>JFIF</code> en su <em>header</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>n_deleted <span class="ot">&lt;-</span> <span class="dv">0</span>L</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(filepath <span class="cf">in</span> <span class="fu">list.files</span>(path, <span class="at">pattern =</span> <span class="st">"</span><span class="sc">\\</span><span class="st">.jpg$"</span>,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">recursive =</span> <span class="cn">TRUE</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  header <span class="ot">&lt;-</span> <span class="fu">readBin</span>(filepath, <span class="at">what =</span> <span class="st">"raw"</span>, <span class="at">n =</span> <span class="dv">10</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">identical</span>(header[<span class="dv">7</span><span class="sc">:</span><span class="dv">10</span>], <span class="fu">charToRaw</span>(<span class="st">"JFIF"</span>))) {</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    n_deleted <span class="ot">&lt;-</span> n_deleted <span class="sc">+</span> <span class="dv">1</span>L</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">unlink</span>(filepath)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"%d imagenes eliminadas</span><span class="sc">\n</span><span class="st">"</span>, n_deleted))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="distribución-de-las-dimensiones-de-las-imágenes" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="distribución-de-las-dimensiones-de-las-imágenes"><span class="header-section-number">3.3</span> Distribución de las dimensiones de las imágenes</h2>
<p>Analizamos los tamaños de las imágenes para determinar el rango de tamaños que contiene el set de datos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionar aleatoriamente 1000 imágenes de muestra</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>sample_file <span class="ot">&lt;-</span> <span class="fu">sample</span>(file_name, <span class="dv">1000</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Ejecutamos la función get_dim() para cada imagen</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>file_dim <span class="ot">&lt;-</span> <span class="fu">map_df</span>(sample_file, get_dim)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(file_dim, <span class="dv">10</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   height width                                   filename
1     500   307   ./db/cats_and_dogs/PetImages/Dog/576.jpg
2     113   150  ./db/cats_and_dogs/PetImages/Dog/5808.jpg
3     500   375  ./db/cats_and_dogs/PetImages/Cat/1616.jpg
4     308   285 ./db/cats_and_dogs/PetImages/Cat/11762.jpg
5     500   375  ./db/cats_and_dogs/PetImages/Cat/1992.jpg
6     500   429 ./db/cats_and_dogs/PetImages/Dog/10007.jpg
7     421   500  ./db/cats_and_dogs/PetImages/Cat/3347.jpg
8     498   500  ./db/cats_and_dogs/PetImages/Cat/5266.jpg
9     331   200  ./db/cats_and_dogs/PetImages/Dog/3097.jpg
10    430   350  ./db/cats_and_dogs/PetImages/Cat/1394.jpg</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(file_dim)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     height          width         filename        
 Min.   : 50.0   Min.   : 56.0   Length:1000       
 1st Qu.:311.8   1st Qu.:325.8   Class :character  
 Median :375.0   Median :472.5   Mode  :character  
 Mean   :363.6   Mean   :407.1                     
 3rd Qu.:426.0   3rd Qu.:500.0                     
 Max.   :500.0   Max.   :500.0                     </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggExtra)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> file_dim <span class="sc">%&gt;%</span> </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>width, <span class="at">y=</span>height)) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"orange3"</span>, <span class="at">fill=</span><span class="st">"orange1"</span>, <span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggMarginal</span>(p, <span class="at">type=</span><span class="st">"density"</span>, <span class="at">color=</span><span class="st">"green4"</span>, <span class="at">fill=</span><span class="st">"green4"</span>, <span class="at">alpha=</span><span class="fl">0.5</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deep_Learning_03_examples_02b_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="uso-de-data-augmentation" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="uso-de-data-augmentation"><span class="header-section-number">3.4</span> Uso de <em>Data Augmentation</em></h2>
<p>Cuando no se cuenta con un conjunto de datos de imágenes <span class="green">suficientemente grande</span>, es una buena práctica introducir diversidad en las muestras de manera artificial aplicando transformaciones aleatorias, pero realistas, a las imágenes de entrenamiento. Ejemplos son giros horizontales o pequeñas rotaciones aleatorias. Esto ayuda a exponer el modelo a diferentes aspectos de los datos de entrenamiento mientras disminuye el sobreajuste (<span class="green">overfitting</span>).</p>
<p>La variable <code>target_size</code> se define como un vector <span class="orange"><span class="math inline">[150, 150]</span></span>, indicando las dimensiones deseadas para redimensionar las imágenes. Este paso de preprocesamiento asegura que todas las imágenes se redimensionen uniformemente a una altura y anchura de 150 píxeles, facilitando dimensiones de entrada consistentes para el modelo.</p>
<p>Además, la variable <code>batch_size</code> se establece en 250. Durante el entrenamiento del modelo, el conjunto de datos se divide en lotes, y cada lote contiene 75 muestras. Esta configuración ayuda a optimizar el uso de la memoria y la eficiencia computacional durante el proceso de entrenamiento.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Altura y ancho deseado para las imágenes</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>target_size <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">150</span>, <span class="dv">150</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Tamaño de "batch" para el entrenamiento del modelo</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>batch_size <span class="ot">&lt;-</span> <span class="dv">250</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2024</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Generador de imágenes</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>train_data_gen <span class="ot">=</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">image_data_generator</span>(<span class="at">rescale =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">255</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">zoom_range =</span> <span class="fl">0.25</span>, <span class="co"># Rango de Zoom_in / zoom_out</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                           <span class="at">validation_split =</span> <span class="fl">0.2</span>, <span class="co"># 20% data para as validación</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                           <span class="at">fill_mode =</span> <span class="st">"nearest"</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>                           <span class="co"># acá se incorporan más tecnicas de data augmentation</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>                           )</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La siguiente configuración está establecida para el generador de datos de imagen <code>train_data_gen</code>:</p>
<ul>
<li><p><code>rescale</code>: Los valores de los píxeles se escalan al rango <span class="orange"><span class="math inline">[0, 1]</span></span> dividiéndolos por 255, lo que estandariza los datos de entrada.</p></li>
<li><p><code>zoom_range</code>: Las imágenes pueden ampliarse o reducirse hasta en un 25%, diversificando aún más el conjunto de datos.</p></li>
<li><p><code>validation_split</code>: Se reserva una porción de los datos (20%) como datos de validación para monitorear el rendimiento del modelo durante el entrenamiento.</p></li>
<li><p><code>fill_mode = "nearest"</code>: Esto especifica cómo se rellenan los valores de los píxeles al aplicar transformaciones como rotación o zoom. <code>"nearest"</code> rellena los valores faltantes con el píxel más cercano.</p></li>
</ul>
<p>Estas técnicas de <span class="orange"><em>data augmentation</em></span>, combinadas con el reescalado y la división de validación, contribuyen a crear un conjunto de datos más robusto y diverso para el entrenamiento. El generador <code>train_data_gen</code> prepara los datos con estas transformaciones, ayudando al modelo a aprender a reconocer patrones y características bajo diversas condiciones y orientaciones.</p>
<p>La variable <code>target_size</code> se define como un vector <span class="orange"><span class="math inline">[150, 150]</span></span>, indicando las dimensiones deseadas para redimensionar las imágenes. Este paso de preprocesamiento asegura que todas las imágenes se redimensionen uniformemente a una altura y anchura de 150 píxeles, facilitando dimensiones de entrada consistentes para el modelo.</p>
<p>Además, la variable <code>batch_size</code> se establece en 250. Durante el entrenamiento del modelo, el conjunto de datos se divide en lotes, y cada lote contiene 75 muestras. Esta configuración ayuda a optimizar el uso de la memoria y la eficiencia computacional durante el proceso de entrenamiento.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataset entrenamiento</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>train_image_array_gen <span class="ot">=</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">flow_images_from_directory</span>(<span class="at">directory =</span> path, <span class="co"># Carpeta de los datos</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">target_size =</span> target_size, <span class="co"># (150 x 150)  </span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>                             <span class="at">color_mode =</span> <span class="st">"rgb"</span>, <span class="co"># también puede ser "grayscale"</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>                             <span class="at">batch_size =</span> batch_size , </span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>                             <span class="at">seed =</span> <span class="dv">100</span>,  <span class="co"># semilla aleatoria</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>                             <span class="at">subset =</span> <span class="st">"training"</span>, <span class="co"># para datos de entrenamiento</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>                             <span class="at">generator =</span> train_data_gen,</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>                             <span class="at">class_mode =</span> <span class="st">'binary'</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>                            )</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Found 18559 images belonging to 2 classes.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataset validación</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>val_image_array_gen <span class="ot">=</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">flow_images_from_directory</span>(<span class="at">directory =</span> path,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">target_size =</span> target_size, </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">color_mode =</span> <span class="st">"rgb"</span>, </span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">batch_size =</span> batch_size ,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>                             <span class="at">seed =</span> <span class="dv">100</span>,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>                             <span class="at">subset =</span> <span class="st">"validation"</span>, <span class="co"># para datos de validación</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>                             <span class="at">generator =</span> train_data_gen,</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>                             <span class="at">class_mode =</span> <span class="st">'binary'</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>                            )</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Found 4639 images belonging to 2 classes.</code></pre>
</div>
</div>
<p>El conjunto de datos se divide en dos subconjuntos: el <span class="orange">Conjunto de Datos de Entrenamiento</span> (<code>train_image_array_gen</code>) y el <span class="orange">Conjunto de Datos de Validación</span> (<code>val_image_array_gen</code>). Cada subconjunto se prepara utilizando la función <code>flow_images_from_directory</code>.</p>
<p>Para el conjunto de datos de entrenamiento:</p>
<ul>
<li>El parámetro <code>directory</code> especifica la carpeta que contiene los datos.</li>
<li><code>target_size</code> define las dimensiones deseadas de la imagen (150 x 150 píxeles).</li>
<li><code>color_mode</code> indica el uso de rgb (3 canales).</li>
<li><code>batch_size</code> establece el tamaño del lote para el entrenamiento (250).</li>
<li><code>seed</code> establece la semilla aleatoria para la reproducibilidad.</li>
<li><code>subset</code> se establece en <code>"training"</code> para designar este subconjunto como datos de entrenamiento.</li>
<li><code>generator</code> especifica el generador <code>train_data_gen</code> para el preprocesamiento y <em>data augmentation</em> (de ser necesario).</li>
</ul>
</section>
<section id="balanceo-de-datos" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="balanceo-de-datos"><span class="header-section-number">3.5</span> Balanceo de Datos</h2>
<p>Mantener proporciones equilibradas de datos en los subconjuntos ayuda a garantizar que el modelo esté expuesto a una variedad representativa de ejemplos durante el entrenamiento, permitiéndole aprender eficazmente entre diferentes clases o categorías. Una proporción adecuada de datos en el conjunto de validación es igualmente importante, ya que asegura una evaluación justa del rendimiento del modelo en datos no vistos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Número de muestras de entrenamiento</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>train_samples <span class="ot">&lt;-</span> train_image_array_gen<span class="sc">$</span>n</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Número de muestras de validación</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>valid_samples <span class="ot">&lt;-</span> val_image_array_gen<span class="sc">$</span>n</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Número de clases/categorías objetivo</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>output_n <span class="ot">&lt;-</span> <span class="fu">n_distinct</span>(train_image_array_gen<span class="sc">$</span>classes)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener la proporción de clases</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Frecuencia"</span> <span class="ot">=</span> <span class="fu">factor</span>(train_image_array_gen<span class="sc">$</span>classes)</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>      ) <span class="sc">%&gt;%</span> </span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prop.table</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Frecuencia
        0         1 
0.5011585 0.4988415 </code></pre>
</div>
</div>
</section>
</section>
<section id="cnns" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> CNNs</h1>
<section id="la-base-del-modelo" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="la-base-del-modelo"><span class="header-section-number">4.1</span> La base del modelo</h2>
<p>Reutilizaremos la misma estructura general: la CNN será una superposición de capas alternadas de <code>layer_conv_2d</code> (con activación <code>relu</code>) y etapas de <code>layer_max_pooling_2d</code>. A medida que se <span class="green">“profundiza”</span>, se aumenta el número de filtros. Esto se debe a que <span class="green">las convoluciones pueden aprender jerarquías espaciales de patrones</span>. Una primera capa de convolución aprenderá <span class="orange">pequeños patrones locales como bordes</span>, una segunda capa de convolución aprenderá <span class="orange">patrones más grandes formados por las características de las primeras capas</span>, y así sucesivamente. Esto permite que las redes convolucionales aprendan de manera eficiente conceptos visuales cada vez más complejos y abstractos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">keras_model_sequential</span>() <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Añadiendo la primera capa de convolución con 16 filtros de 3x3</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Añadimos una dimensión adicional en la forma de entrada ya que las convoluciones operan sobre tensores 3D</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># La forma de entrada le dice a la red que la primera capa debe esperar</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># imágenes de 150 por 150 píxeles con una profundidad de color de 3, es decir, imágenes RGB</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_conv_2d</span>(<span class="at">input_shape =</span> <span class="fu">c</span>(target_size, <span class="dv">3</span>), <span class="at">filters =</span> <span class="dv">16</span>, <span class="at">kernel_size =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>), <span class="at">activation =</span> <span class="st">'relu'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Añadiendo una capa de max pooling que reduce a la mitad las dimensiones</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_max_pooling_2d</span>(<span class="at">pool_size =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Añadiendo una segunda capa de convolución con 32 filtros</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_conv_2d</span>(<span class="at">filters =</span> <span class="dv">32</span>, <span class="at">kernel_size =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>), <span class="at">activation =</span> <span class="st">'relu'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Añadiendo una capa de pooling</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_max_pooling_2d</span>(<span class="at">pool_size =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Aumentando el número de filtros a medida que disminuye el tamaño de la imagen</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_conv_2d</span>(<span class="at">filters =</span> <span class="dv">64</span>, <span class="at">kernel_size =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>), <span class="at">activation =</span> <span class="st">'relu'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_max_pooling_2d</span>(<span class="at">pool_size =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="añadiendo-un-clasificador-a-la-cnn" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="añadiendo-un-clasificador-a-la-cnn"><span class="header-section-number">4.2</span> Añadiendo un clasificador a la CNN</h2>
<p>Las capas convolucionales aprenden las características y las pasan a las <span class="green">capas densas (<em>feed forward</em>, o <em>MLP</em>)</span>, que asignan las características aprendidas a las etiquetas dadas. Por lo tanto, el siguiente paso es <span class="orange">alimentar el último tensor de salida a una red de clasificador</span> densamente conectada como las que ya conocemos: un grupo de capas densas. Estos clasificadores procesan vectores, que son 1D, sin embargo, la salida actual es un tensor 3D. Primero, se debe aplanar las salidas 3D a 1D, y luego agregar algunas capas densas en la parte superior.</p>
<p>Cabe destacar que, dado que nos enfrentamos a un <span class="orange">problema de clasificación de dos clases</span>, es decir, un problema de clasificación binaria, terminaremos nuestra red con una activación sigmoide, de modo que la <span class="orange">salida de nuestra red será un solo escalar entre 0 y 1</span>, codificando la probabilidad de que la imagen actual pertenezca a la clase 1 (en lugar de la clase 0).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">=</span> modelo <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_flatten</span>() <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_dense</span>(<span class="at">units =</span> <span class="dv">512</span>, <span class="at">activation =</span> <span class="st">'relu'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layer_dense</span>(<span class="at">units =</span> <span class="dv">1</span>, <span class="at">activation =</span><span class="st">'sigmoid'</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>modelo <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model: "sequential"
________________________________________________________________________________
 Layer (type)                       Output Shape                    Param #     
================================================================================
 conv2d_2 (Conv2D)                  (None, 148, 148, 16)            448         
 max_pooling2d_2 (MaxPooling2D)     (None, 74, 74, 16)              0           
 conv2d_1 (Conv2D)                  (None, 72, 72, 32)              4640        
 max_pooling2d_1 (MaxPooling2D)     (None, 36, 36, 32)              0           
 conv2d (Conv2D)                    (None, 34, 34, 64)              18496       
 max_pooling2d (MaxPooling2D)       (None, 17, 17, 64)              0           
 flatten (Flatten)                  (None, 18496)                   0           
 dense_1 (Dense)                    (None, 512)                     9470464     
 dense (Dense)                      (None, 1)                       513         
================================================================================
Total params: 9494561 (36.22 MB)
Trainable params: 9494561 (36.22 MB)
Non-trainable params: 0 (0.00 Byte)
________________________________________________________________________________</code></pre>
</div>
</div>
<p>Configuramos el modelo Keras para el entrenamiento (<code>compile</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">compile</span>(</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">loss =</span> <span class="st">'binary_crossentropy'</span>,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">optimizer =</span> <span class="fu">optimizer_rmsprop</span>(<span class="at">learning_rate =</span> <span class="fl">0.001</span>),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">metrics =</span> <span class="st">'accuracy'</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La función de pérdida <code>binary_crossentropy</code> calcula la pérdida de entropía cruzada entre las etiquetas verdaderas y las etiquetas predichas. Se utiliza típicamente cuando <span class="green">solo hay dos clases de etiquetas</span>.</p>
</section>
</section>
<section id="entrenamiento-de-la-cnn" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Entrenamiento de la CNN</h1>
<p>Como hemos visto, este es el proceso donde se “aprende” la relación entre los arreglos <code>train_images</code> y <code>train_labels</code>.</p>
<p>Ajustaremos el modelo a los datos utilizando la función <code>fit</code> para generadores de datos como este. El primer argumento de un generador, que producirá lotes de entradas y objetivos indefinidamente, será cuántas muestras debe tomar del generador antes de declarar el final de una época. Este es el papel del argumento <code>steps_per_epoch</code>. Define el número total de pasos (lotes de muestras) que se deben producir del generador antes de declarar terminada una época y comenzar la siguiente. Generalmente, debería ser igual al número de muestras en tu conjunto de datos dividido por el tamaño del lote.</p>
<p><code>validation_steps</code> describe el número total de pasos (lotes de muestras) que se deben producir del generador antes de detenerse al final de cada época. Le indica a la red cuántos lotes debe tomar del generador de validación para la evaluación.</p>
<p>Una época termina cuando el modelo ha visto <code>steps_per_epoch</code> lotes.</p>
<section id="ajuste-del-modelo-utilizando-un-generador-de-lotes-batch-generator" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="ajuste-del-modelo-utilizando-un-generador-de-lotes-batch-generator"><span class="header-section-number">5.1</span> Ajuste del modelo utilizando un generador de lotes (<em>batch generator</em>)</h2>
<p>Entrenamos por 15 épocas, esto puede tardar unos <em>cuantos minutos</em> en ejecutarse. Además establecemos <code>callbacks</code>. Para revisar en detalle, ver la función <a href="https://tensorflow.rstudio.com/reference/keras/callback_model_checkpoint"><code>callback_model_checkpoint</code></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>epochs <span class="ot">=</span> <span class="dv">30</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Callbacks, para guardar los modelos por época</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co">#callbacks &lt;- list(callback_model_checkpoint(paste0(path,"/save_at_{epoch}.keras"))) </span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>dir_path_train <span class="ot">=</span> <span class="st">"./db/cats_and_dogs/"</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Callbacks, para ir guardando el mejor modelo</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>callbacks <span class="ot">=</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">callback_model_checkpoint</span>( </span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">filepath =</span> dir_path_train, </span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">monitor =</span> <span class="st">"val_loss"</span>, </span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">verbose =</span> <span class="dv">0</span>, </span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_best_only =</span> <span class="cn">TRUE</span>, </span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_weights_only =</span> <span class="cn">FALSE</span>, </span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">mode =</span> <span class="fu">c</span>(<span class="st">"auto"</span>, <span class="st">"min"</span>, <span class="st">"max"</span>), </span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">period =</span> <span class="cn">NULL</span>, </span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_freq =</span> <span class="st">"epoch"</span> </span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>tiempo_ini <span class="ot">=</span> <span class="fu">Sys.time</span>() <span class="co">#Para medir el tiempo de entrenamiento</span></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>history <span class="ot">&lt;-</span> modelo <span class="sc">%&gt;%</span> <span class="fu">fit</span>(</span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>  train_image_array_gen, <span class="co"># Datos entrenamiento</span></span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Número total de pasos (lotes de muestras) que se deben producir</span></span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># antes de declarar terminada una época y comenzar la siguiente.</span></span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">steps_per_epoch =</span> <span class="fu">as.integer</span>(train_samples <span class="sc">/</span> batch_size),</span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Una época es una iteración sobre todos los datos proporcionados</span></span>
<span id="cb41-27"><a href="#cb41-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">epochs =</span> epochs,</span>
<span id="cb41-28"><a href="#cb41-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">callbacks =</span> callbacks,</span>
<span id="cb41-29"><a href="#cb41-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">validation_data =</span> val_image_array_gen,</span>
<span id="cb41-30"><a href="#cb41-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">validation_steps =</span> <span class="fu">as.integer</span>(valid_samples <span class="sc">/</span> batch_size)</span>
<span id="cb41-31"><a href="#cb41-31" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Epoch 1/30
74/74 - 93s - loss: 0.7010 - accuracy: 0.5432 - val_loss: 0.6712 - val_accuracy: 0.6324 - 93s/epoch - 1s/step
Epoch 2/30
74/74 - 98s - loss: 0.6552 - accuracy: 0.6273 - val_loss: 0.6033 - val_accuracy: 0.6871 - 98s/epoch - 1s/step
Epoch 3/30
74/74 - 99s - loss: 0.6061 - accuracy: 0.6699 - val_loss: 0.5655 - val_accuracy: 0.7027 - 99s/epoch - 1s/step
Epoch 4/30
74/74 - 97s - loss: 0.5711 - accuracy: 0.6991 - val_loss: 0.6354 - val_accuracy: 0.6396 - 97s/epoch - 1s/step
Epoch 5/30
74/74 - 101s - loss: 0.5442 - accuracy: 0.7231 - val_loss: 0.5033 - val_accuracy: 0.7491 - 101s/epoch - 1s/step
Epoch 6/30
74/74 - 100s - loss: 0.5165 - accuracy: 0.7388 - val_loss: 0.4749 - val_accuracy: 0.7700 - 100s/epoch - 1s/step
Epoch 7/30
74/74 - 101s - loss: 0.5047 - accuracy: 0.7502 - val_loss: 0.4958 - val_accuracy: 0.7680 - 101s/epoch - 1s/step
Epoch 8/30
74/74 - 101s - loss: 0.4661 - accuracy: 0.7769 - val_loss: 0.6740 - val_accuracy: 0.6829 - 101s/epoch - 1s/step
Epoch 9/30
74/74 - 99s - loss: 0.4605 - accuracy: 0.7785 - val_loss: 0.4507 - val_accuracy: 0.7898 - 99s/epoch - 1s/step
Epoch 10/30
74/74 - 100s - loss: 0.4457 - accuracy: 0.7916 - val_loss: 0.4742 - val_accuracy: 0.7771 - 100s/epoch - 1s/step
Epoch 11/30
74/74 - 97s - loss: 0.4314 - accuracy: 0.7975 - val_loss: 0.4407 - val_accuracy: 0.7953 - 97s/epoch - 1s/step
Epoch 12/30
74/74 - 96s - loss: 0.4125 - accuracy: 0.8077 - val_loss: 0.4299 - val_accuracy: 0.7969 - 96s/epoch - 1s/step
Epoch 13/30
74/74 - 98s - loss: 0.3990 - accuracy: 0.8156 - val_loss: 0.4722 - val_accuracy: 0.7793 - 98s/epoch - 1s/step
Epoch 14/30
74/74 - 97s - loss: 0.3954 - accuracy: 0.8178 - val_loss: 0.4100 - val_accuracy: 0.8118 - 97s/epoch - 1s/step
Epoch 15/30
74/74 - 100s - loss: 0.3758 - accuracy: 0.8289 - val_loss: 0.4363 - val_accuracy: 0.7960 - 100s/epoch - 1s/step
Epoch 16/30
74/74 - 102s - loss: 0.3661 - accuracy: 0.8357 - val_loss: 0.4013 - val_accuracy: 0.8127 - 102s/epoch - 1s/step
Epoch 17/30
74/74 - 96s - loss: 0.3512 - accuracy: 0.8435 - val_loss: 0.3829 - val_accuracy: 0.8269 - 96s/epoch - 1s/step
Epoch 18/30
74/74 - 97s - loss: 0.3356 - accuracy: 0.8514 - val_loss: 0.4329 - val_accuracy: 0.8022 - 97s/epoch - 1s/step
Epoch 19/30
74/74 - 98s - loss: 0.3274 - accuracy: 0.8522 - val_loss: 0.3830 - val_accuracy: 0.8309 - 98s/epoch - 1s/step
Epoch 20/30
74/74 - 100s - loss: 0.3097 - accuracy: 0.8642 - val_loss: 0.3907 - val_accuracy: 0.8251 - 100s/epoch - 1s/step
Epoch 21/30
74/74 - 97s - loss: 0.3050 - accuracy: 0.8676 - val_loss: 0.3678 - val_accuracy: 0.8393 - 97s/epoch - 1s/step
Epoch 22/30
74/74 - 102s - loss: 0.2780 - accuracy: 0.8804 - val_loss: 0.3847 - val_accuracy: 0.8249 - 102s/epoch - 1s/step
Epoch 23/30
74/74 - 98s - loss: 0.2687 - accuracy: 0.8858 - val_loss: 0.3649 - val_accuracy: 0.8416 - 98s/epoch - 1s/step
Epoch 24/30
74/74 - 98s - loss: 0.2603 - accuracy: 0.8887 - val_loss: 0.3788 - val_accuracy: 0.8327 - 98s/epoch - 1s/step
Epoch 25/30
74/74 - 104s - loss: 0.2397 - accuracy: 0.9031 - val_loss: 0.3715 - val_accuracy: 0.8356 - 104s/epoch - 1s/step
Epoch 26/30
74/74 - 100s - loss: 0.2230 - accuracy: 0.9094 - val_loss: 0.3794 - val_accuracy: 0.8393 - 100s/epoch - 1s/step
Epoch 27/30
74/74 - 98s - loss: 0.2033 - accuracy: 0.9183 - val_loss: 0.3797 - val_accuracy: 0.8416 - 98s/epoch - 1s/step
Epoch 28/30
74/74 - 100s - loss: 0.1934 - accuracy: 0.9244 - val_loss: 0.5301 - val_accuracy: 0.8033 - 100s/epoch - 1s/step
Epoch 29/30
74/74 - 98s - loss: 0.1658 - accuracy: 0.9354 - val_loss: 0.5866 - val_accuracy: 0.7769 - 98s/epoch - 1s/step
Epoch 30/30
74/74 - 97s - loss: 0.1616 - accuracy: 0.9381 - val_loss: 0.4133 - val_accuracy: 0.8358 - 97s/epoch - 1s/step</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Es una buena práctica guardar siempre tus modelos después del entrenamiento.</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="sc">%&gt;%</span> <span class="fu">save_model_hdf5</span>(<span class="fu">paste0</span>(dir_path_train,<span class="st">"/cats_and_dogs.h5"</span>)) </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>tiempo_fin <span class="ot">=</span> <span class="fu">Sys.time</span>()</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>tiempo_fin<span class="sc">-</span>tiempo_ini <span class="co"># Tiempo de cómputo</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time difference of 49.4051 mins</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(history)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deep_Learning_03_examples_02b_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Y qué tal le fue a nuestro modelo?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>history</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Final epoch (plot to see history):
        loss: 0.1616
    accuracy: 0.9381
    val_loss: 0.4133
val_accuracy: 0.8358 </code></pre>
</div>
</div>
</section>
</section>
<section id="probando-el-modelo" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Probando el modelo</h1>
<p>Descargaremos algunas imágenes de gatos y perros y veremos qué tan bien nuestro modelo clasifica estas imágenes que nunca antes había visto. Implementación de un generador de datos para las imágenes de prueba</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>test_datagen <span class="ot">&lt;-</span> <span class="fu">image_data_generator</span>(<span class="at">rescale =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">255</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>dir_prueba <span class="ot">=</span> <span class="st">"./db/cats_and_dogs/prueba_gatos_perros"</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>test_generator <span class="ot">&lt;-</span> <span class="fu">flow_images_from_directory</span>(</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">directory =</span> dir_prueba, <span class="co"># La carpeta donde están las imágenes de prueba</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">generator =</span> test_datagen,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">target_size =</span> <span class="fu">c</span>(<span class="dv">150</span>, <span class="dv">150</span>),</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">batch_size =</span> <span class="dv">20</span>,</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">class_mode =</span> <span class="st">'binary'</span>,</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">shuffle =</span> <span class="cn">FALSE</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Found 12 images belonging to 2 classes.</code></pre>
</div>
</div>
<p>Generando predicciones para las muestras de prueba a partir de un generador de datos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> modelo <span class="sc">%&gt;%</span> <span class="fu">predict</span>(</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">steps =</span> <span class="dv">1</span>,</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> test_generator,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbose =</span> <span class="dv">0</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>test_folder_list <span class="ot">=</span> <span class="fu">list.files</span>(dir_prueba)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>test_folder_path <span class="ot">=</span> <span class="fu">paste0</span>(dir_prueba,<span class="st">"/"</span>, test_folder_list, <span class="st">"/"</span>)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>test_image_labels <span class="ot">=</span> <span class="fu">map</span>(test_folder_path, </span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">function</span>(x) <span class="fu">paste0</span>(x, <span class="fu">list.files</span>(x))</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> </span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unlist</span>()</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>image_labels <span class="ot">&lt;-</span> <span class="fu">substring</span>(test_image_labels, <span class="dv">44</span>,<span class="at">last =</span> <span class="dv">61</span>)</span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>pred_results <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(image_labels, predictions)) <span class="sc">%&gt;%</span></span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"Predicción"</span> <span class="ot">=</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"Clase_Predicha"</span> <span class="ot">=</span> <span class="fu">if_else</span>(predictions <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="fu">print</span>(<span class="st">"perro"</span>), <span class="fu">print</span>(<span class="st">"gato"</span>)),</span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">predictions =</span> <span class="fu">as.double</span>(predictions))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "perro"
[1] "gato"</code></pre>
</div>
</div>
<p>A continuación, se muestran las imágenes que utilicé:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EBImage)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>my_images <span class="ot">&lt;-</span> test_image_labels</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="co"># redimensionando las imágenes a una dimensión común según lo requiere readImage {EBImage}</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(my_images)) {</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">readImage</span>(my_images[i]) <span class="sc">%&gt;%</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">resize</span>(<span class="at">w =</span> <span class="dv">500</span>, <span class="at">h =</span> <span class="dv">500</span>) <span class="sc">%&gt;%</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">writeImage</span>(my_images[i])</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>EBImage<span class="sc">::</span><span class="fu">display</span>(</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">readImage</span>(my_images),</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">'raster'</span>,</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">all =</span> <span class="cn">TRUE</span>,</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">nx =</span> <span class="dv">6</span>,</span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">spacing =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Deep_Learning_03_examples_02b_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Predicciones realizadas por el modelo que entrenó durante 15 épocas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>pred_results</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   image_labels           Predicción Clase_Predicha  predictions
1      cat1.jpg 0.000935807998757809           gato 9.358080e-04
2      cat2.jpg  2.1897390979575e-05           gato 2.189739e-05
3      cat3.jpg    0.520951509475708          perro 5.209515e-01
4      cat4.jpg    0.999969065189362          perro 9.999691e-01
5      cat5.jpg    0.919608414173126          perro 9.196084e-01
6      cat6.jpg    0.999941647052765          perro 9.999416e-01
7      dog1.jpg    0.983399569988251          perro 9.833996e-01
8      dog2.jpg    0.999805867671967          perro 9.998059e-01
9      dog3.jpg    0.919475555419922          perro 9.194756e-01
10     dog4.jpg    0.999976634979248          perro 9.999766e-01
11     dog5.jpg    0.999946057796478          perro 9.999461e-01
12     dog6.jpg    0.957095682621002          perro 9.570957e-01</code></pre>
</div>
</div>
<!-- ## Uso de _Data Augmentation_ -->
<!-- Cuando no se cuenta con un conjunto de datos de imágenes [suficientemente grande]{.green}, es una buena práctica introducir diversidad en las muestras de manera artificial aplicando transformaciones aleatorias, pero realistas, a las imágenes de entrenamiento. Ejemplos son giros horizontales o pequeñas rotaciones aleatorias. Esto ayuda a exponer el modelo a diferentes aspectos de los datos de entrenamiento mientras disminuye el sobreajuste ([overfitting]{.green}). -->
<!-- Visualizamos un ejemplo de cómo se verían las muestras aumentadas, aplicando `data_augmentation` repetidamente a la primera imagen del conjunto de datos: -->
<!-- ```{r} -->
<!-- image_size = c(150,150) -->
<!-- data_augmentation = -->
<!--   keras_model_sequential(input_shape = c(image_size, 3)) %>% -->
<!--   layer_random_flip("horizontal") %>% -->
<!--   layer_random_rotation(factor = 0.1) -->
<!-- par(mfrow = c(3, 3)) -->
<!-- for (i in 1:9) { -->
<!--     images[4, , , , drop = FALSE] %>% -->
<!--     data_augmentation() %>% -->
<!--     display_image_tensor() -->
<!-- } -->
<!-- ``` -->
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>